### ISSUE TITLE
Glitches: Mighty Morphin Power Rangers - The Fighting Edition (USA)

### ISSUE THREAD

**Issue by Moonbase1** [SmokeMonsterPacks/Super-NT-Jailbreak#10]
Power Rangers Fighting Edition shows graphical glitches randomly during game play - mostly commonly during the character select screen, and game over screen. Sometimes when a fight loads, the life bars glitch and the game soft locks. Happens with an authentic cartridge as well as a ROM verified good dump.

![unnamed 1](https://user-images.githubusercontent.com/36521759/36284049-297d080e-125b-11e8-938e-3cbe78fb335b.jpg)
![unnamed](https://user-images.githubusercontent.com/36521759/36284059-321f868a-125b-11e8-9564-8dcfd55d7f83.jpg)

**Comment by burk3** [comment]
does this happen on the stock firmware as well?

**Comment by Moonbase1** [comment]
Yes it does

**Comment by Moonbase1** [comment]
Yes

**Comment by frederic-mahe** [comment]
@Moonbase1 , thanks for reporting that bug! Just to be sure we are talking about the same cartridge/ROM, could you please confirm the information below?
```
Mighty Morphin Power Rangers - The Fighting Edition (SNS-A3RE-USA)

ROM's SHA256: 1b85c0690aa156a255c7f79e133e453345452698fa98abf8df744c262d0cf865
ROM'S SHA1:   80a856dba0f12fd1e9eded75d219b854910e990f
ROM's MD5:    bdfcd02f353bc9745dda4556fb7db08a	
ROM's CRC:    460b0a60
```
(confirming one of the checksum values is enough)

**Comment by Moonbase1** [comment]
Yes that's the same ROM.

**Comment by burk3** [comment]
@frederic-mahe I'm curious, is it your intention to accept bugs for the official firmware?

**Comment by frederic-mahe** [comment]
@burk3 bugs affecting the official firmware should be reported to Analogue. This GitHub repository is dedicated to the jailbreak firmware.

That being said, it is likely that bugs affecting the jailbreak firmware will also affect the official firmware, especially graphical glitches or cartridge/ROM specific issues. We report those bugs to Analogue, so they can be corrected in the official firmware too (and eventually in the software emulator higan), for the benefit of the whole community.

**Comment by eabsolidcore** [comment]
In other words they are watching and will fix . Found bugs in prince of Persia and super James pond lag .

**Comment by SmokeMonsterPacks** [comment]
Please re-test this issue with the new official firmware v4.3 using your original cartridge. 

https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v4-3

**Comment by frederic-mahe** [comment]
@Moonbase1 please re-test this issue with the new jailbreak firmware.

**Comment by SmokeMonsterPacks** [comment]
No follow up. Issue marked as resolved.

**Comment by scotthammack** [comment]
I played through three matches using the ROM on JB6.5 and didn't encounter any graphical glitches or soft locks.

**Comment by Moonbase1** [comment]
It takes more than 3 matches sometimes - I will retest tonight

**Comment by SmokeMonsterPacks** [comment]
Thanks for the follow up, Scott!

**Comment by Rahzadan** [comment]
Just tested this for about 30 minutes on both Super Nt 4.4 and Real SNES hardware using SD2SNES to make comparisons. Did not encounter any of the suggested glitches or issues.
