### ISSUE TITLE
Glitches: Mighty Morphin Power Rangers (USA)

### ISSUE THREAD

**Issue by R9delta** [SmokeMonsterPacks/Super-NT-Jailbreak#102]
## Expected behavior and actual behavior

The game has some wierdness going on with what I can best describe as 2 very faint flickering shadows near the bottom that are constantly there throughout the game (at least tested through stage 1 and 2). I haven't tested against a real SNES but any video i've watched of this game seems not to exhibit this issue, including an "Erin Plays" video of this game on an older firmware (though unknown which one) on the Super NT.

## Steps to reproduce the problem

Nothing special needed, just play the game as normal. The character you choose is irrelevant. Issue crops up after the character select screen shows up.

Edit: The visibility of the issue seems to depend on your video settings, at 1080p60 and no scanlines you can barely even see the issue, at 720p60 with scanlines at 120 I can notice but it's faint. without scanlines or with them set to the maximum value it's harder to notice at all. When I initially reported the issue it was pretty noticeable but since doing a restart the problem is still there but it's significantly harder to notice. I'm not sure what I did initially to make the issue more visible so on that note it's kind of hard to reproduce to what degree the problem is noticeable. Honestly at this point it's like overtime the problem has become less and less noticeable on it's own where now I can't even see it anymore. I guess i'll just leave this post here in case anyone else can verify it but i'm kind of scratching my head here now.

## ROM name and hash value

Mighty Morphin Power Rangers (usa).sfc (ran through SD card menu on JB)
MD5: c0a6ae7a3cff034232cb23d765bcb36d
SHA-1: f2b093f57b511fc30d40114649dafc342872186b

## firmware

JB6.6. It is likely that this glitch cropped up more recently and is not on older firmwares. I haven't tested that to verify 100% though.

## relevant Super Nt settings

720p60 + scanlines on (120)
NTSC timing
Launch system timing - off
NTT DATA pad compat. - off
cartridge audio enable - on

**Comment by SmokeMonsterPacks** [comment]
Mufasa and Zoltar007 in Discord tested this and couldn't recreate the problem in JB6.6. Maybe it's something else on your end?
