### ISSUE TITLE
Glitches: Super Star Wars randomly pauses in stage 2 (landspeeder part)

### ISSUE THREAD

**Issue by cacophony1** [SmokeMonsterPacks/Super-NT-Jailbreak#104]
I've seen Super Star Wars unexpectedly pause a number of different times while playing the second stage (landspeeder level). It seems pretty random but the first time I played that level it occurred more than once, and I was able to reproduce the issue again on a subsequent play.  But it is intermittent so may take a few attempts.

To be clear I'm only using the directional pad and Y and B buttons, but the game will act like I just hit Start (pause). At this point the game will remained paused until I hit start, at which point I can resume play.

I'm using an original Nintendo North American wired SNES controller

Based on other reports, this happens on both the rom and original cart.

These comments from -Glitchz might be helpful:

> It seems to be that the up directional button is triggering start somehow. If you press start on that stage and then hold up it will unpause the game too. On other stages holding up after pressing start does nothing.

> On the snt stage 1 if you press start the game pauses and holds. On my 2/1/3 there is a pause/unpause action
On stage 2 the game pauses on its own on the snt but does not on 2/1/3
On the jb the game will unpause on stage 2 by holding up.
But up will not upause if using the cart.

> Easiest way to replicate the ssw issue is to start empire strikes back and enter password  RCWJMF to load the snowspeeder stage or play the first level of return of the jedi.   Same issues reported in ssw.

## ROM
This is using the USA Super Star Wars rom from a recent Smokemonster SNES Everdrive set (v5.2)

## firmware
JB 6.6

**Comment by frederic-mahe** [comment]
Thanks @cacophony1 

Assuming you are referring to *Super Star Wars: A New Hope*:
```
Super Star Wars (USA).sfc
sha256: c6bd7239cb2074ff1c471d14535bead6290bba2d7c75b4f03209cb114877b4c8
sha1:   dbff9bbb155f09376c4c7fe3d68e77c4a444ae3c
md5:    ea840d3722f90dee824f5064e171e510
crc32:  acbcae7c
```
This is indeed a valid dump, confirmed by [byuu](https://preservation.byuu.org/games/Lj4b/l7teQFeO).

**Comment by cacophony1** [comment]
On Discord, Masta_Fu said:

> Yeah, both cart and rom i have the same problem
But with me i didn't have to hit start to resume game
rom version says 1.1, not sure what my cart is
seems to be very rare and very random

And then -Glitchz said:

>  It seems to be that the up directional button is triggering start somehow. If you press start on that stage and then hold up it will unpause the game too. On other stages holding up after pressing start does nothing.

**Comment by cacophony1** [comment]
I also noticed that trying to pause via the start button on the 3rd (?) stage (inside the landspeeder) was kind of difficult, as if it was getting the key twice and then leaving me in an unpaused state. I'll try to investigate this a bit more later...

**Comment by GreatHierophant** [comment]
A tell-tale sign of this behavior is if pressing the pause button firmly does a quick pause/unpause.  You can get a pause to take with a light press of the start button but pressing Up on the D-pad for a second or two will unpause the game during the landspeeder stages.  This behavior also occurs on the snowspeeder stages in SESB.

**Comment by G-lithcz** [comment]
The light pause/unpause action indicated above by GreatHierophant also occurs on real hardware (2/1/3).  What does not occur on real hardware is the unsolicited pauses that randomly occur during the landspeeder stages of all three versions of Super Star Wars. Super Star Wars - stage 2 / Empire Strikes Back - use password RCWJMF / Return of the Jedi - stage 1. One other action that does not occur on real hardware is the ability to unpause during the landspeeder stages by pressing up.  The pause button definitely seems off even on real hardware but these two issues do not occur.

**Comment by frederic-mahe** [comment]
The newly published jailbreak firmware should fix that issue. Could you please confirm @cacophony1 ?

**Comment by lenscritic** [comment]
I tried through Super Star Wars stage 2 twice and didn't experience any unexpected pauses. So it seems fixed to me.

Thank you mysterious JB author! :D

**Comment by cacophony1** [comment]
I played through Super Star Wars stage 2 twice and didn't experience any unexpected pauses. So it seems fixed to me.

Thank you mysterious JB author! :D
