### ISSUE TITLE
Graphical glitch in Seiken Densetsu 2 cave when ballooned by bat

### ISSUE THREAD

**Issue by mantixero** [SmokeMonsterPacks/Super-NT-Jailbreak#106]
## Expected behavior and actual behavior
Graphics glitch when being attacked by bats with a balloon in the cave by the Dwarf Village where you first meet Popoi. It happened while playing with 2 players simultaneously. Did not try it with 1 player only.

![seikendensetsu2glitch](https://user-images.githubusercontent.com/38519777/38974996-c0106166-4371-11e8-81c9-d611975c3ef8.png)

## Steps to reproduce the problem
Play with 2 players in the cave with Popoi and Randy and get ballooned by a bat.

## ROM name and hash value
No-Intro Name: Seiken Densetsu 2 (Japan)
(No-Intro version  20130701-030720)
ROM/File SHA-1: B78A9A844D165345631CEA1B5246C8FCBCDBC162

## firmware

- firmware version: JB 6.6

## relevant Super Nt settings
480p
Zero lag mode
Interpolation disabled

Picking any save file 2 through 4 from the following RAM dump will start you at Kippo Town, from which you can go north to the cave and get ballooned by bats.
[SeikenDensetsu 2.zip](https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/files/1929514/SeikenDensetsu.2.zip)

**Comment by mantixero** [comment]
The issue is also present on real SNES hardware as confirmed in a video by seadona#1221 in the Discord chat, so it isn't specific to the Super Nt.

**Comment by SmokeMonsterPacks** [comment]
Thanks for looking in to it, @mantixero mantixero :D
