### ISSUE TITLE
Features: Improved Video Options

### ISSUE THREAD

**Issue by Firebrandx** [SmokeMonsterPacks/Super-NT-Jailbreak#108]
This is not an issue with games themselves but rather an issue with the menu features that I hope will get back to Kevtris so he can review and make changes:

The "Screen Size" menu (which shows up when you do not have advanced features checked) has options for 1:1 and 8:7 modes, neither one of these modes are useful because they are based on the aspect ratio of the entire image rather than the pixels themselves. As such, for 1:1, you get 960x960 in 4x, which is useless. Nobody would want to 'squish' the active graphics inward for any reason. Additionally, the 8:7 mode is also using strange math that appears to be based on the overscan area of the SNES, and it's throwing off the horizontal res into a useless mode. For example in 4x, it makes the horizontal res 1097. This should be 1024 because true 8:7 is measured from the active graphics of 256x224. You'll often see people tout "8:7' being their favorite way to play SNES on emulators, and what they mean by this is square pixel AR of 256x224 being integer scaled. 

Lastly a feature request needed for Super Game Boy/2 is to extend the vertical all the way to 7x. With square pixels (7x by 7x), this will scale the Super Game Boy/2 to fill the screen vertically on 1080p displays. 

Much appreciated for your consideration on this!

**Comment by SmokeMonsterPacks** [comment]
New screen options have been added in the latest update.
