### ISSUE TITLE
Glitches: CopySNES creates wrong + incomplete dump of Street Fighter Zero 2

### ISSUE THREAD

**Issue by alexcom84** [SmokeMonsterPacks/Super-NT-Jailbreak#109]
Copy SNES is dumping only 3mb of Street Fighter Zero 2 instead of 4mb. Tried dumping Start Ocean and I get a valid ROM, so it's not SSD-1 the issue.
 I get this 3mb ROM: 
CRC32:		0xd8226bb6
MD5:		0x7a53606ac29fee4d3bdd2cea1a86389d
SHA1:		0x20d10d0f0844f7692754ebde5137bbc7ac30e55c

Copy SNES settings:
ROM 4mb
ExLoROM
RAM 0

**Comment by davidpgil** [comment]
I can also add that I have the Japanese Super Famicom cartridge for this game and it doesn't run either. However, SFZ 2 does work with the official Analogue firmware.

(By the way, so far the jailbreak firmware has a lot better compatibility for me than the official one.)

**Comment by ShinKaz** [comment]
> I can also add that I have the Japanese Super Famicom cartridge for this game and it doesn't run >either. However, SFZ 2 does work with the official Analogue firmware.

>(By the way, so far the jailbreak firmware has a lot better compatibility for me than the official one.)

Yeah, no.

https://imgur.com/a/9JAiy6q

**Comment by SmokeMonsterPacks** [comment]
So this works?

**Comment by ShinKaz** [comment]
the car works perfectly fine on my end on JB FW 6.6. (both pal and ntsc-j versions, I don't own the ntsc-u version to test)

as for dumping, I suppose this is still unsolved, I didn't try.

as a side note, I'm pretty sureit is possible to make a "decompressed" rom version of this game and run it on the super nt, like Star Ocean. (you can find the decompressed assets online, I just don't have to knoledge to build the decompressed rom)

**Comment by davidpgil** [comment]
@ShinKaz @SmokeMonsterPacks what @Ghost meant is that the dump doesn't work. I have the Jpanaese cart too and it works fine. Its just that the CopyNES dump doesn't work.

**Comment by SmokeMonsterPacks** [comment]
I'm going to close reports for game that dump incorrectly. If a game doesn't dump right, you need to adjust the settings manually. There will be games that never dump though, and these will not get fixes I'm told.

**Comment by tjanas** [comment]
@alexcom84 @ShinKaz @0xvividmirage CopySNES issue with dumping S-DD1 carts has been reported as fixed, please retest with [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB).

**Comment by alexcom84** [comment]
> @alexcom84 @ShinKaz @0xvividmirage CopySNES issue with dumping S-DD1 carts has been reported as fixed, please retest with [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB).

Yup, it’s fixed in latest fw!
