### ISSUE TITLE
Improvement: load enhancement chip from cartridge to allow full library execution

### ISSUE THREAD

**Issue by LoosGuccreen** [SmokeMonsterPacks/Super-NT-Jailbreak#112]
Note: I have no idea if what I'm asking is only feasible on a technical viewpoint and if it could be feasible in a reasonable amount of time. If I'm asking the impossible, don't hesitate to kill the dream.

---

SNES had this specificity of building chips into the cartridge (such as the infamous Super FX but not only). Currently, [games that use those chips](https://en.wikipedia.org/wiki/List_of_Super_NES_enhancement_chips#List_of_Super_NES_games_that_use_enhancement_chips) are not available through rom loading on super NT (since the enhancement chip are missing).

The idea would be to allow the use of the chip from another cartridge to load the rom.

For example: being able to play Star Fox with a Dirt Racer cartridge in the slot, Star Fox would use the Super FX from Dirt Racer's cartridge.

**Comment by Kethku** [comment]
"Q11: Can enhancement chip XY be realized using a pass-through adapter with the original enhancement chip on top?

A11: The only enhancement chip where that would work is the DSP series (DSP1-4, ST0010) which are already supported natively. All other enhancement chips have the game ROM “behind” them and control access to it, which a cartridge plugged in parallel to the sd2snes cannot do."

The same thing applies here. All enhancement chips except the DSP series interact directly with the rom behind them making it impossible to swap that rom out and use the chip by itself. I could be wrong, but I believe this means that what you propose wouldn't be possible.

**Comment by SmokeMonsterPacks** [comment]
The way that the Super NT Jailbreak works isn't conducive to most special chips. As @Kethku pointed out, the only one that's supposedly feasible might be DSP-1, and even that is an unknown.
