### ISSUE TITLE
Glitches: Rockman X3 sprites disappearing

### ISSUE THREAD

**Issue by mantixero** [SmokeMonsterPacks/Super-NT-Jailbreak#114]
## Expected behavior and actual behavior
Sprites should stay fully visible on screen, but often have portions missing in certain situations.

## Steps to reproduce the problem
Jumping out of a Ride Armor is an easy way to reproduce the issue. Getting hit by an enemy and activating X's shield (once you get the shield upgrade) also tends to show portions of the shield missing. In one cutscene, a couple of Zero's pixels drop in and out.

## Firmware
- firmware version: JB6.6

## Relevant Super Nt settings
I do not have 64-sprite mode enabled.
@seadona#1221 from the Analogue Discord confirmed the issue on his Super Nt, and added that turning 64-sprite mode ON solved the issue.

![rockmanx3-glitch](https://user-images.githubusercontent.com/38519777/39861203-7f0410f6-5405-11e8-9257-982a3b0405a6.gif)
![rockmanx3-glitch2](https://user-images.githubusercontent.com/38519777/39861204-7f140f9c-5405-11e8-9233-f5a640f39ebe.gif)
![rockmanx3-glitch3](https://user-images.githubusercontent.com/38519777/39890772-754e3fda-5461-11e8-902e-1a4ca589e7d6.gif)
![rockmanx3-glitch4](https://user-images.githubusercontent.com/38519777/39891017-305c8886-5462-11e8-8c47-5191f0c9c357.gif)
![rockmanx3-glitch5](https://user-images.githubusercontent.com/38519777/39891027-34c2f1d0-5462-11e8-9637-6a5ad3ff6f6f.gif)

**Comment by frederic-mahe** [comment]
@mantixero I've tested on my 1-chip Super Famicom with an original cartridge and I did not see sprite clipping when shield activates. Can someone else please confirm that there is no clipping on original hardware (ideally, tests should be done on a 2/1/3 NTSC model)?

**Comment by G-lithcz** [comment]
This issue was replicated on a 2/1/3 using an original Rockman X3 cart. Just another example of how faithful the Super NT truly is. In order to avoid this on the SNT just enable the 64 sprite tiles setting.
