### ISSUE TITLE
Feature Request: Save State Support?

### ISSUE THREAD

**Issue by davidpgil** [SmokeMonsterPacks/Super-NT-Jailbreak#115]
Will Super NT Jailbreak ever support save states? For example, in a game where it never had the ability to save, can you add the ability to save at any point in the game?

My particular interest is when I play Super Street Fighter II, I would like for the high-scores to be saved even though the game originally doesn't have a save function.

**Comment by frederic-mahe** [comment]
Here is a quote from discord (user `Bits n Stuff` - May 11, 2018 at 22:22)
> [save state] was discussed on here previously by members and contributors and I believe what was decided was that it may be possible but the time needed to do it well would make it unlikely that it did happen.
> Also, save states would likely be more unstable on a system like this in comparison to pure emulation so even if they did the work to support  having them on an emulated system like the Nintendo minis so if people were relying on them they may actually cause more problems than they solve for people.
>It was a while ago this was discussed but that's the way I remember it, hopefully if one of the tech guys involved in the discussion remembers it they give a better explanation than I could. :wink:
