### ISSUE TITLE
Feature Request: System level pause, and single frame advance

### ISSUE THREAD

**Issue by Neroon** [SmokeMonsterPacks/Super-NT-Jailbreak#116]
Option to have the game paused at the system level similar to what a software emulator can support.

This would be helpful option to have game paused when opening up the Super NT system level menu overlay even if game does not support a pause that point, such as in a cutscene. This would allow to see changes settings have on on screen items that may not be persistent such as graphics glitch 

It is also helpful for playing games in other languages and trying to read an item that is autoscrolling with no in game way to pause.

**Comment by SmokeMonsterPacks** [comment]
Pause coupled with a single frame advance would be very useful for testing games' input latency. Then you could pause the game, hold a button, and advance frames individually to see how many frames it takes for the game to react.
