### ISSUE TITLE
Glitches: Slayers - Doesn't load SAV file

### ISSUE THREAD

**Issue by JaydeSix** [SmokeMonsterPacks/Super-NT-Jailbreak#117]
Game: Slayers (Super Famicom)
md5: 1b7b9b3eabe1008bad9dc19dcad9142f

On JB6.6 saves fail to load properly.
Using the original cart it loads to a black screen.
When running off an sdcard patched with Dynamic Designs translation patch v1.01, saves load to a garbled screen. This happens no matter what sdcard speed is toggled.

Both the save with the translation patch and the sav from the original cart (using Super Nt's copysnes) load fine in retroarch using bsnes (accuracy) core.

**Comment by Jayde6** [comment]
To help out with the verification process I have included both save files and a picture of what happens with the translation patch.

The saves may need to be renamed as appropriate (possibly including extension).
The game will start on the continue option (if it detects the save).
You want to choose the first option that comes up (in case you aren't using the translation patch and like me can't read Japanese). 
The save should be the first option after that.

One more curious thing, when loading the save that was on the cartridge originally the beginning stage music plays on the black screen, but when loaded correctly in an emulator different music plays as it is a different zone.

[saves.zip](https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/files/2107853/saves.zip)
![slayers dynamic designs patched](https://user-images.githubusercontent.com/39748732/41495476-0e28a7bc-70dd-11e8-8f8c-892a20c00d80.jpg)

**Comment by Jayde6** [comment]
I was looking at the compatibility list for loading games on to the snes classic mini and saw that this game has a patch to make the saves work correctly on it. I tried it on a Dynamic Designs 1.01 patched game and it made the saves work correctly on the Super Nt. It failed to work on the unpatched rom though. Hopefully this can lead to a fix for the Super Nt firmware.

**Comment by SmokeMonsterPacks** [comment]
This is a problem with the translation patch.

**Comment by Jayde6** [comment]
It's not. The original cartridge does this with a save saved on a super famicom and a save saved from the super nt.

**Comment by Jayde6** [comment]
Looking through the romhacking forums, the patch creator posted that the patch fixes:

`Slayers: 83/a49d = sei. Doesn't prevent nmi from firing inside sram load / save routine. Force it off and no more timing crash.`

and then later:

`nmi firing within nmi`

**Comment by Jayde6** [comment]
Adding: Same results on snt Firmware V4.8, black screen and starting area music playing when loading a super famicom saved save on an original cartridge.

**Comment by mrdiamondblade** [comment]
I know this is almost one year old, but may I ask what type of SNES are you using? Cause I'm able to save and load on an Emulator just fine.

**Comment by Jayde6** [comment]
> 
> 
> I know this is almost one year old, but may I ask what type of SNES are you using? Cause I'm able to save and load on an Emulator just fine.

This was on the Super Nt. The save that was on the cartridge when I bought it, as well as the save I saved on the Super Nt both worked fine on an emulator for me too. The Super Nt won't load the saves properly though. A handful of emulators used to have the same problem but most fixed it a long time back.

There still hasn't been a fix for this with the Super Nt though, I had emailed their support line directly about it too a year ago. I've purchased the parts to build a Mister FPGA unit and when it all gets here I plan on testing it on there as well.

**Comment by mrdiamondblade** [comment]
That makes a lot of sense then. The Super NT isn't an official console, and would have issues. Do you by any chance have a flash cart such as an Everdrive? If not, are you using an official Slayers cartridge?

**Comment by Jayde6** [comment]
> 
> 
> That makes a lot of sense then. The Super NT isn't an official console, and would have issues. Do you by any chance have a flash cart such as an Everdrive? If not, are you using an official Slayers cartridge?

I don't have a flash cart. I'm using an official Slayers cartridge, I also tried dumping the rom using the Super Nt and it wouldn't load saves correctly through the jailbreak firmware either. The files hash matched no-intros list so the Super Nt should be reading the cart correctly I'd think.

**Comment by mrdiamondblade** [comment]
Would it help if I sent you my rom file for Slayers? Maybe your rom is corrupted.

**Comment by Jayde6** [comment]
I appreciate the offer but since the hash of the rom I dumped from the cartridge matches no-intro there should not be any corruption. Plus I used it in an emulator and it loaded the saves fine. 

The fact that a handful of emulators had the same issue at first as did the emulator in the SNES Classic Edition, pretty much shows that it is a problem with the Super Nt's programming. The cart does a weird thing that an original snes is cool with but the Super Nt is not accurate enough to original hardware to react the same way.

**Comment by NotSoNooby** [comment]
Well, now I'm upset that Slayers wont work on an SNES Classic. I was gonna add it. Now that I think about it, it could be the battery in your cartridge, or the Super NT can't handle games from Japan. Also, if I gave you the hash of my rom, could you check if it works with the Super NT?

**Comment by Jayde6** [comment]
While good ideas, it's not a bad battery and the Super Nt can play Japanese games, it's just this one particular game and any other that might do this weird save thing.

If you want to put it on the SNES Classic someone made a patch for the game that makes it work. It's designed for a rom that has the translation patch already applied. The same patched rom will also make the game work on the Super Nt. I have it linked in my third post up above. So it's cool that it can work but patching games to get them to work isn't ideal.

My first post up above also has the md5 hash for my copy, you can compare your hash to that to see if it might be different. That's also the same hash that no-intro lists as being good.

**Comment by NotSoNooby** [comment]
Ok. I know this sounds stupid, but how do I get my hash? Also, another stupid question, have you tried the patch?

**Comment by Jayde6** [comment]
I've tried the patch on the Super Nt but not the SNES Classic.
To get a hash for your rom you will need a program to do it, there are lots of free ones. I use the program ExactFile. 
There will be a spot to do a single file checksum and you can uncheck any other types besides md5, otherwise it will take forever.

**Comment by NotSoNooby** [comment]
ok. Ill try it later. in the meantime, maybe look up on google patches for the super nt.

**Comment by NotSoNooby** [comment]
Im now reading through the previous comments, which save are you using? Cause maybe your save is corrupted. Are you able to make a new game, and then save that? Maybe try to delete every single save on the cart.

**Comment by Jayde6** [comment]
I'm using a save that was on the cart when I bought it, that was saved on a super famicom and a save that I saved after starting a new game on the Super Nt. Both saves load fine in an emulator.

**Comment by Jayde6** [comment]
Just reporting in that the MiSTer can handle saves for this game fine without the save fix patch.

**Comment by Jayde6** [comment]
Did this get fixed in the new firmware? Cause it's not on the list. If it's not fixed this is still an open issue.

**Comment by SmokeMonsterPacks** [comment]
It's an unofficial romhack, correct?

**Comment by Jayde6** [comment]
No the hack allows saves to work on the super nt, the non patched game has the issue

**Comment by tjanas** [comment]
@JaydeSix can you test an original cartridge with the latest official firmware? https://www.analogue.co/support/super-nt/firmware/5.1

**Comment by JaydeSix** [comment]
> @JaydeSix can you test an original cartridge with the latest official firmware? https://www.analogue.co/support/super-nt/firmware/5.1

Can't, sold my Super Nt a while back.

**Comment by tjanas** [comment]
In that case, I will close the issue as it was reported as fixed on the change log.

**Comment by bsstephan** [comment]
@tjanas - I also have a Slayers cart and experienced the same issue, if I get a chance to mess with it soon I can/will report back.
