### ISSUE TITLE
Feature request: auto power on

### ISSUE THREAD

**Issue by mashers** [SmokeMonsterPacks/Super-NT-Jailbreak#118]
I'm building my SuperNT into an original Super Nintendo housing. I've got it to fit perfectly and adapted the ports on the back. The power switch makes and breaks the +5v power to the SuperNT. I now want the SuperNT to power on immediately when power is applied, without having to press the power button. I don't know if this is possible in firmware, but hopefully if it is, it can be implemented. The alternative would be to solder onto power connections on the SuperNT and use some kind of time delay circuit to close a relay to simulate pressing the power button, but I'd rather not have to do this.

**Comment by SmokeMonsterPacks** [comment]
Kev has commented before that the powe switch is a hard switch and isn't controlled by software, so applications like this aren't possible.
