### ISSUE TITLE
Super Bomberman - Panic Bomber W

### ISSUE THREAD

**Issue by krizp40** [SmokeMonsterPacks/Super-NT-Jailbreak#121]
I am using the original cartridge.
When I boot up the game I get a yellow screen.

You cannot use the mouse with this game.

I am using an original Super Famicom controller and no other devices connected

**Comment by tmagri** [comment]
This issue seems related to #90

**Comment by SmokeMonsterPacks** [comment]
Yes, this is the same as issue #90
