### ISSUE TITLE
Feature Request:  Recents and/or Favourites list

### ISSUE THREAD

**Issue by derkommutator** [SmokeMonsterPacks/Super-NT-Jailbreak#124]
For those who have relatively large ROM collections on SD card, the directory structure can get pretty large.  It would be nice if we had available a recents list and/or a favourites list to jump right back to the ROMs we play the most.

**Comment by frederic-mahe** [comment]
Hi @derkommutator, your feature request echoes ShinKaz's proposition (issue #43). I am going to close this issue, but your feature request will remain visible using [filters](https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3Aenhancement+).
