### ISSUE TITLE
Glitches: Wild Guns (USA)

### ISSUE THREAD

**Issue by black-francis** [SmokeMonsterPacks/Super-NT-Jailbreak#126]
## Expected behaviour and actual behaviour

During the in game shooting sections a single black pixel can be seen moving rapidly back and forth on the lower right hand side of the playable area, just above the wooden bezel which holds the players lives, time remaining etc. 

Issue not present on either Higan or Snes9x but needs testing on real hardware.

## ROM name and hash value

Wild Guns (USA)
                         
ROM MD5 94D30063D9B17567D32079E766251569        
ROM SHA-1 1ECF28D5F3D2E84E3CC58ED621CB0FC0DD9D70D0
ROM CRC32 085D8D14                                

## firmware

 snt_firmware_verJB6.6

## relevant Super Nt settings

Issue is seen with all tested settings.

**Comment by frederic-mahe** [comment]
could be linked to #125 ?

**Comment by frederic-mahe** [comment]
@black-francis I see the same flickering pixel when playing on a Super Famicom 1CHIP-1 with a SD2SNES.
