### ISSUE TITLE
Glitches: Pocky & Rocky (USA)

### ISSUE THREAD

**Issue by black-francis** [SmokeMonsterPacks/Super-NT-Jailbreak#128]
## Expected behaviour and actual behaviour

During the character selection screen a set of pixels can be seen moving rapidly back and forth in the area circled below. Similar to the issue seen in Wild Guns (#126) and Shounen Ahibe (#125).

![img_4108a](https://user-images.githubusercontent.com/44230562/47652158-20a6d700-db7d-11e8-8289-4c31cf276078.jpg)

Issue not present on either Higan or Snes9x but needs testing on real hardware.

## ROM name and hash value

Pocky & Rocky (USA)
                         
File MD5      E74E067787723BC54093A9C03F290E5D        
File SHA-1    DB9D670B6D1915C9F2B26D369B831B1023B33270
File SHA-256 72b2b3bead3fcd27a1610ad5d4d8be3235efeaff96df2e7858911992a5892d21
File CRC32    2B0E7EA3                                                          

## firmware

 snt_firmware_verJB6.6

## relevant Super Nt settings

Issue is seen with all tested settings.

**Comment by frederic-mahe** [comment]
@black-francis I see the same two flickering pixels when playing on a Super Famicom 1CHIP-1 with a SD2SNES.

Someone would need to confirm that issue using a NTSC SNES that is not a 1CHIP. Ideally, one should test a SNES with CPU-2/PPU1-1/PPU2-3 which is what the Super Nt implements.
