### ISSUE TITLE
Does not load saves from Super Everdrive v1 cart SD card

### ISSUE THREAD

**Issue by jloco** [SmokeMonsterPacks/Super-NT-Jailbreak#129]
## Issue

The github states the fw supports and will use/load/save saves from a Super Everdrive cart, but it does not recognize my saves.

I'm using a SD from a SEDv1 cart, the fw does not load game saves from the existing data on the SD.

## firmware

- firmware version: 6.6

**Comment by SmokeMonsterPacks** [comment]
Saves are definitely working, please re-read the README and make sure your folders are arranged properly
