### ISSUE TITLE
Jailbreak FW 4.7 - feature request

### ISSUE THREAD

**Issue by drtekGER** [SmokeMonsterPacks/Super-NT-Jailbreak#133]
Hi, 

could you please jailbreak FW 4.7?

Thanks!

**Comment by tatundria** [comment]
Why did you close it? Isn’t it possible?

**Comment by frederic-mahe** [comment]
@tatundria official firmware v4.7 fixes a gameboy audio bug. We'll see if that can be done in a future jailbreak firmware. In the meantime, there is no need to keep that issue open.
