### ISSUE TITLE
Mega SG Jailbreak Firmware is out!!!  Thanks

### ISSUE THREAD

**Issue by DwaineGarden** [SmokeMonsterPacks/Super-NT-Jailbreak#135]
Tested out the Mega SG jailbreak firmware 7.3.   Works great.  I also like the Colecovision core.
I still have to test out different mega cd bios that you can setup.

Thanks....  Having a lot of fun....

**Comment by frederic-mahe** [comment]
Thanks for your feedback @DwaineGarden 

I am going to close that issue. Please open an issue on the [Mega Sg jailbreak repository](https://github.com/SmokeMonsterPacks/Mega-Sg-Jailbreak) if you find jailbreak related bugs.
