### ISSUE TITLE
Aspect Ratio of the UI is inconsistent between File Browser (Browse SD Card) and all other menus

### ISSUE THREAD

**Issue by SquarePixels** [SmokeMonsterPacks/Super-NT-Jailbreak#136]
## Expected behavior and actual behavior
Aspect Ratio of the UI is inconsistent between File Browser (Browse SD Card) and all other menus

## Steps to reproduce the problem
Simply switch back and forth between the menus to see the difference.
[https://streamable.com/1kzad](https://streamable.com/1kzad)

## Firmware
JB6.6

## relevant Super Nt settings
Tested on 720p and 1080p

**Comment by Jayde6** [comment]
This still happens on JB6.9

**Comment by eturquin** [comment]
I have encountered the same issue.

**Comment by re4mat** [comment]
Still happens in 5.0 / JB7.0
