### ISSUE TITLE
Glitches: Unholy Night (Unl)

### ISSUE THREAD

**Issue by Moonbase1** [SmokeMonsterPacks/Super-NT-Jailbreak#14]
Unholy  Night when in a fight will randomly turn the screen into garbage. Once the fight ends, the graphics return to normal. On official firmware the game hangs before the title screen.

ROM DATA ROM CRC32: DF99025E

Have attempted to play with cartridge and game loads and plays, have not confirmed if the cart glitches as well

**Comment by frederic-mahe** [comment]
@Moonbase1 , I don't know this game (name or CRC32 not found). Could you please give more info? (NTSC or PAL? cartridge serial, etc.)

**Comment by Moonbase1** [comment]
![67fd615b-0f16-45ca-a896-46f5fba3a9f6](https://user-images.githubusercontent.com/36521759/36300213-22f3dbfc-12b5-11e8-9963-7984064c356d.jpeg)

Error confirmed with original cartridge

**Comment by Moonbase1** [comment]
It is a indie game released this year on cartridge. NTSC. Analogue told me they bee aware of it not running on firmware 3.9, and they were working on it. With this JB firmware it lets you play but graphical glitches.

**Comment by SmokeMonsterPacks** [comment]
Please re-test this issue with the new official firmware v4.3 using your original cartridge. 

https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v4-3

**Comment by RevQuixo** [comment]
I was able to getting halfway through the first fight before the background glitched out.  Then in the 2nd fight my sprite disappeared and the screen started jumping around.   Still broken under 4.3

**Comment by SmokeMonsterPacks** [comment]
No follow up. Issue marked as resolved.

**Comment by Moonbase1** [comment]
DId not have a chance to retest until now - background still glitched on new JB 6.5 lasted half a round.

**Comment by SmokeMonsterPacks** [comment]
Thanks, reopened

**Comment by SmokeMonsterPacks** [comment]
Kev has Unholy Night fixed in the next official firmware update.

**Comment by SmokeMonsterPacks** [comment]
This has been fixed in v4.4

**Comment by SmokeMonsterPacks** [comment]
RevQuixo dumped his European region Unholy Night cart via CopySNES and it crashes after finishing the first match. 
MD5: ffe5445ac39f30efc397899351d12b07

**Comment by SmokeMonsterPacks** [comment]
I'm going to open a new issue for this since Unholy Night is now fully working, it just isn't dumping correctly due to faulty ROM programming by the developers.
