### ISSUE TITLE
Glitches: Mario to Wario sky graphic glitch

### ISSUE THREAD

**Issue by Chronokeys** [SmokeMonsterPacks/Super-NT-Jailbreak#142]
## Behavior:
Top half of the sky of the main menu changes color when choosing a different mouse speed.

![unnamed-2](https://user-images.githubusercontent.com/53979082/62825694-7f21cc80-bb75-11e9-9288-b0b533e00a39.jpg)

## Expected Behavior:
Sky must remain unchanged
![unnamed-1](https://user-images.githubusercontent.com/53979082/62825729-fc4d4180-bb75-11e9-8998-33ca6f731715.jpg)

## Steps to reproduce 
Very easy but requires an snes mouse. On the menu simply keep choosing a different mouse speed, low or high, and the sky will change its color. Dont know if it's relevant but this was encountered using a hyperkin snes mouse.

Firmware:
JB 6.9

Rom:
Mario to Wario (Japan).sfc

md5:
d41d8cd98f00b204e9800998ecf8427e

Stock SNT settings

**Comment by tjanas** [comment]
Does this happen with version 6.7 of the firmware?

**Comment by tjanas** [comment]
FYI I was unable to recreate this with a real SNES mouse and JB 6.7.

**Comment by Chronokeys** [comment]
This happened to me on JB 6.7 also, weird, maybe the hyperkin mouse is to blame?

**Comment by frederic-mahe** [comment]
@Chronokeys thanks for reporting that issue.

Could you please double-check the MD5 of your ROM? *Mario to Wario* (Japan) (En)'s MD5 should be B1774F03700DFC311BFD86411DB629C3 (see [no-intro](https://datomatic.no-intro.org/?page=show_record&s=49&n=1563)).

d41d8cd98f00b204e9800998ecf8427e is the MD5 of *Taekwon-Do* (Korea).

**Comment by Chronokeys** [comment]
The rom I was using gave that exact md5: d41d8cd98f00b204e9800998ecf8427e, so I went and got the rom with the correct md5: b1774f03700dfc311bfd86411db629c3
Don't know why the previous rom gave that value, probably a bad dump, so I retested the new rom on the SNT and the bug is still happening in exactly the same way. 

This is what I'm doing: load the game, unplug controller in port 1, plug in hyperkin snes mouse (that always sends a button press input btw), then I do the steps to reproduce as described above and the sky glitches out. Maybe someone who owns both original and hyperkin snes mouse could test to see if somehow this could be triggered by the 3rd party mouse?

**Comment by frederic-mahe** [comment]
Thanks for checking @Chronokeys 

There is an entry in SmokeMonster's pack for the SNES with the MD5 hash d41d8cd98f00b204e9800998ecf8427e and the name *Taekwon-Do* (Korea). This is probably a misnamed ROM then.

**Comment by frederic-mahe** [comment]
As @Chronokeys suggested, this is what needs to be verified next:
> Maybe someone who owns both original and hyperkin snes mouse could test to see if somehow this could be triggered by the 3rd party mouse?

**Comment by Rahzadan** [comment]
Snt Firmware:
Official 4.9

SD2SNES OG (non-Pro) - Firmware 1.10.3

I can confirm that this issue only seems to occur when using the Hyperkin SNES mouse, and it also happens on real hardware! This issue is not related to Super NT firmware in any way. I tested on my 2-1-3 SNES. See the video I made below:

[https://youtu.be/9CBeCxE1I98](url)

**Comment by frederic-mahe** [comment]
Thanks @Rahzadan ! To summarize, the issue occurs on the Super Nt and the original SNES when using the Hyperkin SNES mouse, but not when using an original SNES mouse. This is not specific to the Jailbreak firmware or to the Super Nt, but rather an issue with the Hyperkin SNES mouse.
