### ISSUE TITLE
Light gun support via Wiimote with the use of 8Bitdos Bluetooth adapter.

### ISSUE THREAD

**Issue by BarbieOnWeed** [SmokeMonsterPacks/Super-NT-Jailbreak#146]
Light gun support via Wiimote with the use of 8Bitdos Bluetooth adapter.
Any chance this would be possible?
I know there is no sensor bar, but if there is any other way?
Its a long shot, i know.

**Comment by tjanas** [comment]
I don't see this happening for many reasons, so @frederic-mahe I recommend closing this issue.
