### ISSUE TITLE
Better handling of NTSC/PAL switching

### ISSUE THREAD

**Issue by mankeli** [SmokeMonsterPacks/Super-NT-Jailbreak#148]
I have lots of backups on the sd card that are NTSC only, but most of my carts are PAL. It's quite annoying to always to the menu and switch the region.
I wonder if it could be handled automatically? 

Or atleast so that cart port would be always PAL but sd card files are NTSC.

**Comment by SmokeMonsterPacks** [comment]
This didn't show up in the latest update so I'm closing the request to focus attention on bugs.
