### ISSUE TITLE
Prepare FAQ

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/Super-NT-Jailbreak#15]
So that people would not post similar questions over and over again.

I mean things like this: https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/issues/4

Or like this: https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/issues/9

Of course, consult this with the dev behind the jailbroken firmware.

**Comment by jan-kleks** [comment]
@SmokeMonsterPacks @frederic-mahe Also, you might want to talk with the dev behind the jailbroken firmware about using this GitHub as **the** bug tracker, looking for various bugs through forums and YouTube comments can get really messy at times. And users sometimes even don't know whether their bug has already been reported or not...

**Comment by SmokeMonsterPacks** [comment]
I'd rather keep all of the relevant info in the README.
