### ISSUE TITLE
"Tactics Ogre - Let Us Cling Together" romhack hangs upon select-down

### ISSUE THREAD

**Issue by mortimerprime** [SmokeMonsterPacks/Super-NT-Jailbreak#152]
## Expected behavior and actual behavior
Down-select "saving" causes the system to hang with the bottom-right "saving icon" spinning for a long time (1min+). Music continued, but no other keypresses worked. Had to hard reset the system.

## Steps to reproduce the problem
Upon loading patched rom in the Super NT with newest Jailbreak firmware applied (v6.9) and then pressing down-select, the system appears to hang with the bottom-right "saving icon" spinning for a long time (1min+). Music continued, but no other keypresses worked. Had to hard reset the system.

## ROM name and hash value
original rom = "Tactics Ogre - Let Us Cling Together (J) (V1.2).sfc"
patch = https://www.romhacking.net/translations/1501/

Note; I was able to run and properly down-select the unpatched rom. Rom can be provided if needed. Could not get FCIV utility to work (not installed on my native version of Windows)

## firmware
v6.9

- firmware version: 

## relevant Super Nt settings
default

**Comment by SmokeMonsterPacks** [comment]
Rom hacks are always going to be problematic.
