### ISSUE TITLE
Send save RAM back to cart with CopySNES 

### ISSUE THREAD

**Issue by BarbieOnWeed** [SmokeMonsterPacks/Super-NT-Jailbreak#155]
Any chance for an updated version of CopySNES to have the ability to transfer saves back to the cart.
Have alot of old emulator saves and on Super NT I would love to use on original carts. :)

**Comment by GunbusterZero** [comment]
If you can't wait for this feature like me, I would recommend looking into the Retrode 2, with this device it is possible to copy almost all saves back to an snes cart.

**Comment by JediWed** [comment]
[x] Vote for this :-)

**Comment by Drakonas** [comment]
> If you can't wait for this feature like me, I would recommend looking into the Retrode 2, with this device it is possible to copy almost all saves back to an snes cart.

Before you willy nilly recommend a product I would do research first. The Retrode 2 doesn't support most special chip games, specifically any where the special chip manipulates SRAM (which is, again, most). If you want this feature 100% you'll instead want a fully-outfitted Sanni Cart reader, but they are diy projects only. You'll have to find someone that can build it for you if you can't.

**Comment by tjanas** [comment]
@BarbieOnWeed @SaberSage @turcane @Drakonas please retest with [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB). This feature has been added.
