### ISSUE TITLE
Set HDMI content type to 'game'

### ISSUE THREAD

**Issue by skooterblog** [SmokeMonsterPacks/Super-NT-Jailbreak#156]
HDMI specification allows for sources to specify the content type to be sent to the display, so it can automatically adjust viewing modes. Playstation 4 and other consoles set the content type to 'game', so the TVs in 'auto mode' can automatically enter the low latency 'game mode'.

On the other hand, Super Nt doesn't set content type, so the 'game mode' has to be manually selected. It would be nice if Analogue Super Nt could send the content type too.

**Comment by SmokeMonsterPacks** [comment]
This didn't show up in the latest update so I'm closing the request to focus attention on bugs.
