### ISSUE TITLE
Feature Request - Hide File Extensions 

### ISSUE THREAD

**Issue by Bits-n-Stuff** [SmokeMonsterPacks/Super-NT-Jailbreak#164]
Feature Request - Hide File Extensions 
A selectable and saveable option to hide file extension types while browsing ROMs, a common option on flash carts.
There may be times it's beneficial to see the file extension so a on/off option would be ideal but most of the time the extensions serve no purpose.

EXAMPLES:
**Hide File Extensions  (Off)**
Super Mario Kart (USA).sfc
Super Mario RPG - Legend of the Seven Stars (USA).sfc
Super Mario World (USA).sfc

**Hide File Extensions  (On)**
Super Mario Kart (USA)
Super Mario RPG - Legend of the Seven Stars (USA)
Super Mario World (USA)

Would of course be equally as valid for the Nt Mini and Mega Sg jailbreaks but I'm not sure if you want me to post in all three?

**Comment by SmokeMonsterPacks** [comment]
This didn't show up in the latest update so I'm closing the request to focus attention on bugs.
