### ISSUE TITLE
7.0 firmware zip does not contain special chip bios files

### ISSUE THREAD

**Issue by schrock** [SmokeMonsterPacks/Super-NT-Jailbreak#166]
It appears that the 7.0 firmware zip file does not contain the bios files in the BIOS folder. The 6.9 firmware zip does include these files. Are they no longer required with the 7.0 firmware, or does the 7.0 zip file need to be updated to include these bios files?

**Comment by tjanas** [comment]
They will have to be obtained elsewhere.
