### ISSUE TITLE
README.md has a typo in the Changelog

### ISSUE THREAD

**Issue by re4mat** [SmokeMonsterPacks/Super-NT-Jailbreak#167]
"Fixed non-visble top scanline in HDMI"

Should be:

"Fixed non-visible top scanline in HDMI"

(This is also present on Analogue's [official 5.0 firmware changelog](https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v5-0), but at least we can fix it here. 🙂)

**Comment by frederic-mahe** [comment]
thanks, this is fixed now
