### ISSUE TITLE
Widescreen possible?

### ISSUE THREAD

**Issue by SpaceAgeHero** [SmokeMonsterPacks/Super-NT-Jailbreak#170]
Is it possible to add Widescreen support, just like [bsnes-hd](https://github.com/DerKoun/bsnes-hd)?

Some games already work pretty well, others are getting impressive patches.
Watch [Super Metroid Widescreen](https://www.youtube.com/watch?v=amjZmBsIvO8)

**Comment by SmokeMonsterPacks** [comment]
This isn't possible.
