### ISSUE TITLE
Suggestion: GBA game support

### ISSUE THREAD

**Issue by RealEMK** [SmokeMonsterPacks/Super-NT-Jailbreak#173]
I'm pretty new to FPGA emulation, but from what I understand it allows you to emulate the hardware of specific consoles for more accurate emulation than software emulation.

My question is, is it possible to implement a mod that allows you to boot into some sort of GBA mode that lets you boot up GBA rom files and changes the hardware emulation to match .gb and .gba files?

**Comment by RealEMK** [comment]
Sorry in advanced if I didn't use the correct flag. New to Github and I'm still learning to use the interface properly.

**Comment by tjanas** [comment]
I don't think this is going to happen and seems to be out of scope for the Super Nt.

**Comment by RealEMK** [comment]
Any reason in particular you think this is out of it's scope?
