### ISSUE TITLE
Save instructions

### ISSUE THREAD

**Issue by cmcavoy** [SmokeMonsterPacks/Super-NT-Jailbreak#174]
The README says, "When a game is exited to the menu, it will prompt you to save. Return to the file menu and save your progress before powering down." That option was turned off in settings. To get the prompt, I had to turn it on. Would suggest either turning it on as the default, or including the need to turn it on in the README.

Otherwise, this firmware is fantastic...thanks a bunch

**Comment by tjanas** [comment]
Submit a pull request with your documentation change.

**Comment by cmcavoy** [comment]
@tjanas added: https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/pull/183

Thanks!

**Comment by tjanas** [comment]
Fixed via https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/pull/183
