### ISSUE TITLE
Glitches: Clock Tower (JP) character portrait error

### ISSUE THREAD

**Issue by ovenroll** [SmokeMonsterPacks/Super-NT-Jailbreak#178]
## Expected behavior and actual behavior
**Expected Behavior**: Main Character portrait should change color in respect to your character status, not corrupt. For example:
![correct display 3](https://user-images.githubusercontent.com/83162876/115990006-ff16f100-a5fb-11eb-8062-2269fd69ec05.jpg)
![correct diplay 1](https://user-images.githubusercontent.com/83162876/115990008-00481e00-a5fc-11eb-881e-fee2a6c20bd7.jpg)
![Correct display 2](https://user-images.githubusercontent.com/83162876/115990009-00e0b480-a5fc-11eb-99a2-ab21c85efc78.jpg)

**Actual Behavior**:
Upon entering a new room the main characters portrait is corrupted, and turns a bright orange color. Sometimes it will change back very quickly, other times it will lock this way until you change rooms.
![incorrect display 2](https://user-images.githubusercontent.com/83162876/115990054-37b6ca80-a5fc-11eb-8c4c-a6e308632c9f.jpg)
![incorrect display 1](https://user-images.githubusercontent.com/83162876/115990055-38e7f780-a5fc-11eb-941d-750a277054ef.jpg)

## Steps to reproduce the problem
Progress until the first bedroom with the two beds, birdcage and mirror. Enter and exit this room through the right side door a few time until the issue occurs. 

## ROM name and hash value
Clock Tower (Japan).sfc
File MD5      51F8A9E95EC58FA5B9C3EC2DA530D598        
File SHA-1    FEB998D4E963A76A4DEE6351EDAB894AF431EEBA
File CRC32    CBCD0DAD                                
ROM MD5       51F8A9E95EC58FA5B9C3EC2DA530D598        
ROM SHA-1     FEB998D4E963A76A4DEE6351EDAB894AF431EEBA
ROM CRC32     CBCD0DAD                                

Unable to verify if this bug occurs with a cartridge or not

## firmware
- firmware version: 
Version 7.0 Feb 14 2021
(jailbreak)
## relevant Super Nt settings
Stock settings

**Comment by GreatHierophant** [comment]
I can reproduce that orange reverse portrait effect on two original SNES consoles using an sd2snes, so whatever the issue is, it is not due to the Super Nt.
