### ISSUE TITLE
CopySNES Stunt race fx (Pal) save game not working

### ISSUE THREAD

**Issue by Ramzanox** [SmokeMonsterPacks/Super-NT-Jailbreak#180]
CopySNES on Stunt race fx (Pal version) copys the game and save game, but only the game works but not the save game.

**Comment by ssshake** [comment]
I'm curious about this, I don't understand. This is a SFX chip game so how is it that you are saying the game works after backup? It shouldn't work at all right?

**Comment by alexcom84** [comment]
What this user means is SRAM dumping isn't working. It's broken since fw 6.9 and downgrading to 6.6 works as intended. 
 Reproduced this issue with SA-1 games and SPC7110 Far East of Eden (should affect all special chip games).

**Comment by tjanas** [comment]
@Ramzanox can you please re-test with [JB7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB/releases/tag/v7.2)?

**Comment by tjanas** [comment]
If issue still exists, please report the issue at the [analoguejb](https://github.com/analoguejb/Analogue-Super-Nt-JB) repository.

**Comment by Ramzanox** [comment]
Tested today copysnes on stunt race fx (pal version) with JB7.2 and sadly the save doesnt still work when i tested it on computer.
________________________________
Lähettäjä: Terry Janas ***@***.***>
Lähetetty: tiistai 11. heinäkuuta 2023 21.56
Vastaanottaja: SmokeMonsterPacks/Super-NT-Jailbreak ***@***.***>
Kopio: Ramzanox ***@***.***>; Mention ***@***.***>
Aihe: Re: [SmokeMonsterPacks/Super-NT-Jailbreak] CopySNES Stunt race fx (Pal) save game not working (#180)


Closed #180<https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/issues/180> as completed.

**Comment by Ramzanox** [comment]
Tested today with retrode 2 to dump game+savegame and seems atleast on emulators that the savegame doesnt work, on real snes console and Super Nt my game works.
