### ISSUE TITLE
Feature Request: Menu Option to Load Last Loaded ROM

### ISSUE THREAD

**Issue by ssshake** [SmokeMonsterPacks/Super-NT-Jailbreak#182]
Upon booting up the SuperNT I would like an option to load the last played rom. Possibly between the Load Cartridge and Browse SD menu items.

I would really appreciate this feature when playing RPGs. When you have hundreds of roms, upon boot, having to scroll through the list just to load the same rom every time is a little annoying.

This is something that I have grown to appreciate about my Super Everdrive. Now they do it for technical reasons, the ROM is already flashed, no reason to go through the list just to reflash the same thing. But still it was a nice convenience.

I feel like there's a bit of psychological piece to it too. Just like a physical cartridge being a top level item, having your current rom as a top level item makes it feel more... valuable/special.

**Comment by tjanas** [comment]
What I usually do on my SD2SNES and other flash carts is create a directory called `0 Favorites` and I place RPGs I'm actively playing and other games I frequently play. No scrolling necessary.

**Comment by ssshake** [comment]
I do the same. This is a different thing in my eyes. These aren't favorites, it's just an account of what I last played. 

I might not play a game for a week or two at a time, it's nice to come back and be like, "Oh yeah I was in the middle of Chrono Trigger". 

I would love an on board feature rather than having to drop the sd card in my PC to move things by hand. 

If you don't wish to implement it that's fair, I just figured I'd throw the idea out there in case it had any appeal.
