### ISSUE TITLE
Backing out of SPC player doubles frame rate in 720p modes

### ISSUE THREAD

**Issue by Ramsis-SNES** [SmokeMonsterPacks/Super-NT-Jailbreak#189]
Set video resolution to one of the 720p modes, then go to the SPC player and leave again by tapping the cancel button as many times as needed (twice, usually). Using the Start button instead to bring up the menu from within the SPC player won't trigger the issue.

The menu appears, but only if your TV supports a doubled frame rate. My Samsung LED TV complains about an unsupported resolution.

Result when starting out in 720p60:

![Screenshot (4)](https://user-images.githubusercontent.com/11965591/120906680-b53e1380-c65b-11eb-9543-9cb6fdafafc6.png)

And 720p50:

![Screenshot (5)](https://user-images.githubusercontent.com/11965591/120906696-d6066900-c65b-11eb-9c37-b7462ce19123.png)

1080p modes don't seem to be affected. On the other two modes available when using my capture device (480p60 and 576p50), the picture/signal won't recover at all ("waiting for signal" animation plays, no resolution/fps specs below video window).

Oh, and also: https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/issues/157 confirmed.

**Comment by tjanas** [comment]
@Ramsis-SNES please retest with [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB).
