### ISSUE TITLE
Save Question: Can't read SRM, but writes SRM.

### ISSUE THREAD

**Issue by Llorean** [SmokeMonsterPacks/Super-NT-Jailbreak#19]
So, a follow up to "saves have to be in .sav format," I created an sd2snes\saves folder, and put my .sav files in there. Later I checked the folder and found some .srm files in it, created by other games I'd played.

So... does what file extensions it recognizes vary based on what folder the files are in? This seems extra confusing, now.

**Comment by SmokeMonsterPacks** [comment]
No follow up. Issue marked as resolved.
