### ISSUE TITLE
Feature Request: Custom Console Settings Presets

### ISSUE THREAD

**Issue by RykinPoe** [SmokeMonsterPacks/Super-NT-Jailbreak#195]
A super handy feature would be the ability to basically setup all the various options on your Super Nt (this could apply to all of the Analogue products actually) and then save it as a custom preset so you can quickly toggle between presets. There are some base settings that work great on most games, but stuff like the Super Game Boy and certain games tend to look/work better with slightly different console settings (like adjusting the vertical position when using the 5x scaling options).

The way I kind of seeing this working is that you setup everything the way you want it and then in the Save menu it gives you the option to Save As System Preset. If you select this it asks if you want to create new or overwrite existing. If you create new you provide a name like "Super Game Boy" or whatever and then it creates a file on the SD Card inside a presets folder and overwrite will just let you select one of the existing ones to overwrite. Then in the Settings menu probably as the top item would be a Presets option that would load the Presets folder and allow you to quickly swap between them. On system startup it would load a Default.settings (or whatever extension works best) located in the presets folder or perhaps an option to Load Last Used Preset by default. The settings files would just be text or xml or json whatever is easiest to work with on these systems, but also easy to tweak in a text editor on a computer and easy to share.

One final extra feature that would be great but that might be asking too much is to be able to automatically switch to a certain preset when specific carts/roms are run. I have no idea if there is an easy way to detect which cartridge/rom is being run (other than generating a hash, which might be too slow) though so this might not be doable. Roms could be done by looking for a <same file name>.settings file either next to the rom or in a rom_presets folder with an option in the Save menu to Save As ROM Preset when running a rom. Would probably want a way to either specify a System Preset or a full settings file by having it so if the first thing in the file is something like load_preset="/presets/Super Game Boy.settings" it knows to just load that preset if it exists on that system, but if that line isn't there then it would be a full settings file unique to that game.

**Comment by lucaslealdev** [comment]
As an MVP it would be enought to have 5 slots, not named. Presets 1 to 5 would be enough to get it working and the devs could allow renaming them later as this is not really necessary.
