### ISSUE TITLE
Cannot get BIOS directory to work for special chip games no matter what. Please help. 

### ISSUE THREAD

**Issue by Genjin77** [SmokeMonsterPacks/Super-NT-Jailbreak#203]
I am running version 7.0. I obtained the BIOS folder that contained all the .bin files from the previous firmware. I have the folder in the root of my SD card and followed the instructions provided but special chip games will not work. Keep getting the 'expansion not supported!' error. Please provide specific instructions and steps for a fix. I downgraded to version 6.9 but it still doesn't work. Any information is appreciated, really can't find any info on this problem.

**Comment by tjanas** [comment]
@Genjin77 please ask for assistance in the [Classic Gaming Discord](https://discord.gg/UDu5ztY) in the Super Nt channel.
