### ISSUE TITLE
 jailbreak firmware 7.X for new Super NT Firmware?

### ISSUE THREAD

**Issue by Shadow322** [SmokeMonsterPacks/Super-NT-Jailbreak#204]
will there be a new jailbreak firmware for the just released update to the Super NT?

**Comment by Rot-gut** [comment]
I hope so!

**Comment by tjanas** [comment]
No need to create a ticket for this.

**Comment by tjanas** [comment]
@Shadow322 @Rot-gut [JB v7.2](https://github.com/analoguejb/Analogue-Super-Nt-JB).
