### ISSUE TITLE
Donkey Kong Country 3 cartridge won't load w/ 7.0

### ISSUE THREAD

**Issue by JohnWestlund** [SmokeMonsterPacks/Super-NT-Jailbreak#205]
Cartridge loads with this message:

This Product will not operate when connected to device which makes unauthorized copies. 
Please refer to your instruction booklet
for further information.

**Comment by tjanas** [comment]
You may need to [clean your cartridge](https://www.reddit.com/r/snes/comments/e7oj5d/got_this_error_when_i_put_in_donkey_kong_country/).
