### ISSUE TITLE
Glitches: Monopoly Community Chest (USA) (Rev 1)

### ISSUE THREAD

**Issue by coughlanio** [SmokeMonsterPacks/Super-NT-Jailbreak#21]
Possible bug/glitch with Monopoly (from the SD2SNES pack, CRC matches), in two player mode, when getting a community chest card, the game appears to hang, with no way to progress.

**Expected Behavior**

Can proceed through a full game of Monopoly without issue, including when getting a community chest card.

**Actual Behavior**

Game hangs after receiving a community chest card.

**Comment by frederic-mahe** [comment]
Thanks for reporting this bug @coughlanio 

Could you please confirm the ROM is _Monopoly_ (USA) (Rev 1)?
```
sha1: beddd101739f5e1a6e3abd1542cccd341e6e5263
md5: f478e1eddc87352ed35205d6cfe017ce
crc32: 88d54085
```

The corresponding cartridge would then be _Monopoly_ (`SNS-ML-USA`, revision `SNS-ML-1`). To check whether or not the bug also affects the official firmware, it would be great if someone could check with an official cartridge.

**Comment by coughlanio** [comment]
That is indeed the version 👍

**Comment by Jagasian** [comment]
I am able to reproduce this issue using official Super NT firmware 4.1 and sd2snes firmware 0.1.7e.  The game also locks up when getting a chance card.

**Comment by Jagasian** [comment]
I downgraded to SNT firmware 4.0 and the game no longer locks up when the Chance or Community Chest animation is played, but there is still an issue.  The animation exits back to the board a second after it is started, so it is impossible to see what card you just picked up.

**Comment by Jagasian** [comment]
The bug still repros in firmware version 4.3

**Comment by frederic-mahe** [comment]
thanks for your feedback @Jagasian

**Comment by frederic-mahe** [comment]
That bug should be solved now with the new jailbreak firmware. Please, give it another try @coughlanio

**Comment by SmokeMonsterPacks** [comment]
Holdmybeer on Discord confirmed this has been resolved
