### ISSUE TITLE
Crash: Home Alone (USA)

### ISSUE THREAD

**Issue by scotthammack** [SmokeMonsterPacks/Super-NT-Jailbreak#23]
- Load Home Alone (USA).sfc
- On title screen, start a new game
- Press start to skip the intro cinematic
- As soon as the game starts, the screen goes black and the game does not respond to input. The music continues playing. The Super NT menu is still accessible.

SHA1: e1f96f63603f4d899ec8e29975d0cdf0170cde73
MD5: 87447e71a602b02797054a4d80349c20

Unfortunately I don't have a real cartridge to test against.

**Comment by frederic-mahe** [comment]
@scotthammack , thanks for reporting that bug. I've checked against byuu's [dump database](https://preservation.byuu.org/), and that's a valid ROM.

It would be ideal if someone could test the real cartridge on a Super Nt with an official firmware.

**Comment by Ghettoblaster81** [comment]
Confirmed working. USA cart on original firmware.
![img_5623](https://user-images.githubusercontent.com/25824665/36354442-d4421cd6-14d4-11e8-93db-d648cdd01e98.jpg)

**Comment by SmokeMonsterPacks** [comment]
@scotthammack Could you please test using a different SD card if possible?

**Comment by scotthammack** [comment]
Replicated using the same ROM loaded off a 4GB Toshiba MicroSD-HC card. The results were identical to my initial report.

**Comment by SmokeMonsterPacks** [comment]
@Ghettoblaster81 Please re-test this issue with the new official firmware v4.3 using your original cartridge. 

https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v4-3

**Comment by Ghettoblaster81** [comment]
@SmokeMonsterPacks it wasn't me with the error, that was @scotthammack 

I just tested it with the original cart that worked on original 4.0 firmware. I guess it still works on 4.3 firmware. Will update my firmware asap.

**Comment by frederic-mahe** [comment]
The new jailbreak firmware should fix that crash. Please, give it another try @scotthammack .

**Comment by scotthammack** [comment]
Confirmed fixed on JB6.5 firmware.
