### ISSUE TITLE
Glitches: Super Adventure Island (USA)

### ISSUE THREAD

**Issue by scotthammack** [SmokeMonsterPacks/Super-NT-Jailbreak#24]
- Load Super Adventure Island (USA).sfc
- Start the game
- The background graphics for the first level are glitched out.
![img_20180217_095749](https://user-images.githubusercontent.com/17106568/36344064-92518dd6-13c9-11e8-9d6a-852dd88933c7.jpg)

SHA1: 74a3671878b1d7c8b3fd5a14677c16b2d5566af0
MD5: 206e6c5c05ac1a83dde21400325a4a7d
I don't have a cartridge to compare to.

**Comment by frederic-mahe** [comment]
Hash value matches byuu's dump database.

**Comment by cacophony1** [comment]
I do not see this issue with the Super Adventure Island rom that I have (which came out of a recent Everdrive pack off archive.og). But it looks like mine has a different SHA1 and MD5 value.

**Comment by scotthammack** [comment]
Oddly, after reading @cacophony1's comment, I tried again and this issue didn't occur. I have no idea why it would have changed. Maybe it just didn't load the ROM correctly when I first got the issue, for whatever reason?

I guess this bug can be closed?

**Comment by SmokeMonsterPacks** [comment]
Thanks for the follow-up. It could very well be SD card related, since MSU1 functionality in SD2SNES is very picky about that. If it crops up again, maybe try another fast card.
