### ISSUE TITLE
Game saves do not work after powering the system off & on

### ISSUE THREAD

**Issue by siskavard** [SmokeMonsterPacks/Super-NT-Jailbreak#25]
I was able to successfully save games, reset the system from the menu, then load the saves. However, now that I've turned the system completely off then on again, none of the games can 'see' the saves, even though the browser shows that they are in the correct directory.

**Comment by konradklaus** [comment]
I too have experienced this problem.  I checked and the save file was written, but it is empty.

**Comment by SmokeMonsterPacks** [comment]
This is being covered in #2
