### ISSUE TITLE
Cartridge Dumping

### ISSUE THREAD

**Issue by TheRealFlamepanther** [SmokeMonsterPacks/Super-NT-Jailbreak#26]
This is a feature request to add support for dumping ROM and SRAM from the cartridge port to the SD card. Writing SRAM from SD to cartridge would also be tremendously useful (e.g. after replacing a battery).

**Comment by SmokeMonsterPacks** [comment]
For now we are holding off on feature requests, since that can get out of control. I can re-open this at a later date though because it is a feature that a lot of people would want.

**Comment by SmokeMonsterPacks** [comment]
Cartridge dumping is now possible via the CopySNES feature in JB v6.6
