### ISSUE TITLE
Crash: Samurai Spirits (Japan)

### ISSUE THREAD

**Issue by Videodr0me** [SmokeMonsterPacks/Super-NT-Jailbreak#29]
Samurai Spirits JP crashes after initial logo - sometimes cherry blossom animation shows for a fraction of a second before crash. JB load.

**Comment by frederic-mahe** [comment]
@Videodr0me could you please indicate a hash value for the ROM? or are you using a cartridge?

**Comment by Videodr0me** [comment]
SHA256: 208d65dbae14cc8a6d02df00528cb3d6cc67a3b84538a2141cdb949160239ecc
same file works on higan

**Comment by SmokeMonsterPacks** [comment]
Could someone please re-test this issue with the new official firmware v4.3 using an original cartridge?

https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v4-3

**Comment by SmokeMonsterPacks** [comment]
No follow up. Issue marked as resolved.

**Comment by Videodr0me** [comment]
Works on JB6.5

**Comment by SmokeMonsterPacks** [comment]
Thanks for the follow-up, Videodrome
