### ISSUE TITLE
Does not recognize .srm saves

### ISSUE THREAD

**Issue by Llorean** [SmokeMonsterPacks/Super-NT-Jailbreak#3]
Not really an "issue" but if you copy over saves from something that uses the extension .srm, this firmware won't see them. Solving it is as simple as renaming them to .sav, but in the section of the documentation that describes where to put your saves, it might be worth mentioning this (or updating the firmware to check for both extensions).

**Comment by frederic-mahe** [comment]
thanks for your feedback @Llorean 

The need for a `.sav` file extension is now mentioned in the README (see commit af0cd29d24e6001377051a9febafe3272e9210c3). A future firmware might support more file extensions.
