### ISSUE TITLE
Feature Request - remapping controller inputs

### ISSUE THREAD

**Issue by steeleforge** [SmokeMonsterPacks/Super-NT-Jailbreak#34]
## Expected behavior and actual behavior
Desired behavior is to have a "Controller Mapping" sub-menu under Controls & Hot-Keys, persisted per controller port. Background for this request is that RetroReceiver + 8Bitdo N30 Arcade Stick (DINPUT mode) has a mirror image button layout for face buttons. X is where Y should be and A is where B should be. Remapping would be delightful.

## Steps to reproduce the problem
N/A not a defect

## ROM name and hash value
N/A

## firmware version and SD card model
- Jailbreak firmware v6.4
- default settings

**Comment by SmokeMonsterPacks** [comment]
This is a nice suggestion but we're trying to focus the Issues tracker on bugs, so I have been closing feature requests to keep things focused.
