### ISSUE TITLE
Improvement: Hide File Extensions in Menu

### ISSUE THREAD

**Issue by Bits-n-Stuff** [SmokeMonsterPacks/Super-NT-Jailbreak#35]
**REQUESTED FEATURE**
A quality of life option in Settings > System > Menu Options to hide the ROM format (.SFC / .SMC)  while navigating an SD card. A simple On/Off switch would suffice.

**REASON**
It reduces the clutter in ROM lists and reduces the length of the ROM title.

**Comment by SmokeMonsterPacks** [comment]
Closing minor feature requests to shift the focus back on bugs.
