### ISSUE TITLE
Feature Request: Ability to Swap Functionality of Power & Reset Button on Console

### ISSUE THREAD

**Issue by cacophony1** [SmokeMonsterPacks/Super-NT-Jailbreak#36]
## Request

I'd like to have a toggle in the menu that swaps the functionality of the physical power and reset buttons on the console. So if enabled, pressing power will cause a reset and pressing reset will turn the console on/off.

## Reason

These two switches are the only movable parts on the console, and movable parts tend to wear out and fail over time. Nobody needs the physical reset switch, so if in the future the power switch fails it would be nice to be able to use the reset button instead.

**Comment by masterninjah** [comment]
its a mechanical switch, they're usually rated for at least 10 million clicks.  good luck wearing that out.

**Comment by cacophony1** [comment]
I've had a mechanical switch fail after around 1000 uses so problems do occur sometimes.

**Comment by frederic-mahe** [comment]
@cacophony1 you are thinking long-term and I appreciate that. However, wouldn't it be better to replace the failing mechanical switch? I assume Analogue design's uses standard parts.

**Comment by cacophony1** [comment]
@frederic-mahe well the switches are physically mounted onto the board so I assume that fix would require some desoldering/soldering skill (plus sourcing the correct part, which might be difficult): https://pbs.twimg.com/media/DWBchQoXcAMoIrH.jpg:large

**Comment by SmokeMonsterPacks** [comment]
This is a nice suggestion but we're trying to focus the Issues tracker on bugs, so I have been closing feature requests to keep things focused.

**Comment by frederic-mahe** [comment]
@cacophony1 maybe Analogue can provide the specifications and references of the mechanical switches? You don't have much to loose in asking them.

**Comment by cacophony1** [comment]
Good idea, it's worth a shot!
