### ISSUE TITLE
Improvement: "Save Game Written to SD Card" Menu Notification

### ISSUE THREAD

**Issue by TheYokai** [SmokeMonsterPacks/Super-NT-Jailbreak#37]
I'm not sure if this is possible for you to add to the system, but it would be nice if a notification appeared when a save game is saved onto the SD card and, similarly, when it fails to write the save game to the SD card. This may help resolve confusion over game save functionality when loading from ROM.

**Comment by chipperkwah** [comment]
This would be great. I've opened the menu, assumed the save was written, and lost my save a few times now.

**Comment by iancourt** [comment]
Perhaps customisable, to appear in top/bottom/left/right corner, as a user preference, to avoid obstructing any in-game HUD.

**Comment by SmokeMonsterPacks** [comment]
This feature is included in v6.5
