### ISSUE TITLE
Super Nt firmware update v4.3

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/Super-NT-Jailbreak#38]
Analogue released a new [official firmware (v4.3)](https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v4-3).

**Comment by romevi** [comment]
So this just flashes over the jailbreak, right? If I have the jailbreak installed, flashing the new official firmware won't cause any known issues, correct?

**Comment by frederic-mahe** [comment]
yes @romevi you can flash any version of the official or jailbreak firmware at anytime. The Super Nt is designed to be "unbrickable". As long as you follow the flashing protocol, you should not have any problem.

**Comment by joneslee85** [comment]
@frederic-mahe are we expecting a jailbreak version on top of v4.3?

**Comment by frederic-mahe** [comment]
There is a new official firmware in town! (see issue #46)
