### ISSUE TITLE
Feature Request: Box Art Rom Browser

### ISSUE THREAD

**Issue by neonstreetlight** [SmokeMonsterPacks/Super-NT-Jailbreak#39]
This one feels like a stretch based on what I know about how the Super Nt works, but it would be pretty amazing to be able to browse roms on an SD card by visually scrolling through the box art for each game.

**Comment by romevi** [comment]
A lot of work to get them loaded for each game. It would be easier to make the feature available and let users upload it, but I feel this crosses too much into emulator territory. 

The SNt is a standalone SNES and the jailbreak is just a nice bonus. The official digital games Turrican 1 and 2 don't have digital box arts anyway.

**Comment by SmokeMonsterPacks** [comment]
This is a nice suggestion but we're trying to focus the Issues tracker on bugs, so I have been closing feature requests to keep things focused.
