### ISSUE TITLE
N64 Roms?

### ISSUE THREAD

**Issue by swt83** [SmokeMonsterPacks/Super-NT-Jailbreak#4]
Will this device / mod eventually support N64 roms?  Is this even possible?

**Comment by hectorvs** [comment]
not possible, FPGA is for 16bit processors.

**Comment by anpage** [comment]
> FPGA is for 16bit processors.
This isn't true. It just so happens that the FPGA in the SNt is too small to handle the complexity of most 32-bit and higher processors.

**Comment by hectorvs** [comment]
> This isn't true. It just so happens that the FPGA in the SNt is too small to handle the complexity of most 32-bit and higher processors.

makes sense! 

either way, answer to OPs question is still no.

**Comment by swt83** [comment]
Sad panda.
