### ISSUE TITLE
Improvement: Export Option For System Configuration

### ISSUE THREAD

**Issue by Bits-n-Stuff** [SmokeMonsterPacks/Super-NT-Jailbreak#41]
**REQUESTED FEATURES**
- An option to save custom multiple configuration files (Resolution/Scanlines/Audio Settings/Etc) and define a custom name. For example saving one and calling it "720p, Integer Scaling with Scanlines" and being able to save multiple configuration files which you can then choose to load when desired.
- Add the ability to back configurations up to SD card for convenience.
- Custom configurations that are created while with a particular game and then saved would automatically be loaded up next time you boot that game. This may be an unreasonable request due to difficulty. 

**REASON**
User convenience, it's always useful to have backups of your settings once you've found the ideal configuration for a particular game

**Comment by SmokeMonsterPacks** [comment]
Closing minor feature requests to shift the focus back on bugs.
