### ISSUE TITLE
Improvement: Integer Scaling Lock

### ISSUE THREAD

**Issue by B9KnM8UqQ2W2Vwk7uvZ7** [SmokeMonsterPacks/Super-NT-Jailbreak#42]
**REQUESTED FEATURES**
Additional "Integer Scaling Lock" tick box, perhaps in Width & Height options.

Ticking this box will allow you to switch _only_ through the different levels of integer scaling that are available for your selected resolution, you would so this using the _Start_ button. Almost like it is now in the Width setting but instead of integer scaling only changing on the Width slider, it would simultaneously also change the Height setting each time you move through the Width integer scaling pre-sets.

**REASON**
For people who are only happy using integer scaling, it means not having remember or search online for the correct vertical pixel count that you wish to use.

**Comment by SmokeMonsterPacks** [comment]
Something similar to this was included in v4.4
