### ISSUE TITLE
Community Discord Server

### ISSUE THREAD

**Issue by SouthpawGamer** [SmokeMonsterPacks/Super-NT-Jailbreak#44]
Not an issue just wanted to post the creation of a Super Nt Community Discord server.  

https://discord.gg/EX57xnF

_That link will never expire.  Feel free to share it._

----------------------

It was created today (March 1st) so is still in the early phases of being setup properly.  Would love some help with that if anyone has the drive for it.  

Feel free to let KEVIN LEE know if you're one of the people behind the jailbreak firmware and I'll be sure to make tags for those of you contributing to the Super Nt community.  The end goal is just to have a place outside of Github / Reddit / various forums to discuss the Super Nt and anything related to the hardware.

May as well get all of us in one location if we can.

**Comment by SmokeMonsterPacks** [comment]
Frederic-mahe added a note about the Discord server in the readme.
