### ISSUE TITLE
Improvement: 1:1 should simulate square pixels

### ISSUE THREAD

**Issue by jaysylvester** [SmokeMonsterPacks/Super-NT-Jailbreak#45]
## Expected behavior and actual behavior

The term "1:1" used by the retro community commonly refers to pixel ratio (square pixels). Seeing this label, the user working with the community definition assumes square pixel simulation by utilizing the same multiplier in both directions (240x256 -> 1200x1280, so 5x in both directions).

However, the Super Nt's 1:1 setting represents an aspect ratio and makes height and width the same (1200x1200 display pixels), which doesn't simulate square pixels.

The expected behavior is that using the 1:1 setting would use the same multiplier for horizontal as used in the vertical height setting.

There was also some discussion about changing the label on this setting to something like "Simulate Square Pixels" since every other ratio in the UI (4:3, 16:9) refers to aspect ratio, making 1:1 a confusing label to those unfamiliar with its usage in the retro community.

## Steps to reproduce the problem

Enable 1:1 in the menu with any vertical multiplier. Width will be set to the same display pixel value as vertical rather than an equal multiplier.

## firmware version and SD card model

Affects all versions.

**Comment by jaysylvester** [comment]
"Aspect ratio" anywhere else in the video chain refers to display aspect ratio, not pixel. I know the retro community calls it that when referring to pixels, but any typical user would find that description confusing.

**Comment by cacophony1** [comment]
I don't care what it's called, but practically speaking there are some people who want square pixels, but I don't think anybody is interested in a square display ratio.

**Comment by jaysylvester** [comment]
The main reason I'm suggesting a label change is because the label is for the "easy" standard menu, which is what less technical users will work with. The enhanced settings make it possible to set a custom 1024x960 or 1280x1200 size if that's what someone wants, and I'd assume advanced users have already figured that out if it's important to them.

It should be evidence enough that the term "1:1" is confusing since kevtris himself took it to mean an aspect ratio and not pixel ratio, and he's a pretty smart dude.

**Comment by cacophony1** [comment]
Makes sense. I like the idea of calling it "square pixels" to avoid confusion.

**Comment by frederic-mahe** [comment]
That's a request for the official firmware. This is an interesting discussion but I am going to close this issue as it does not concern a jailbreak feature in particular.

**Comment by jaysylvester** [comment]
We've been told to report issues with the official firmware here as well. Is there somewhere else we should be suggesting improvements other than Discord/AtariAge?

**Comment by jaysylvester** [comment]
No problem, just wondering. Thanks for answering 👍
