### ISSUE TITLE
Glitches: Soul Blazer (USA) Audio lags like a 1chip

### ISSUE THREAD

**Issue by scotthammack** [SmokeMonsterPacks/Super-NT-Jailbreak#58]
When starting Soul Blazer (USA), the beginning of the title screen music sounds slightly lagged/slowed down for the first few seconds as the title is scrolling across the screen. I don't have a way to test on my SNES, but according to Great Hierophant on Discord, "Something like that can happen on original SNES consoles, but intermittently.  With the 1chip SNES consoles and the Super Nt it happens all the time. The opening music did not lag on my 3-chip 2/1/3 through my sd2snes"

For reference, it sounds like [this video](https://www.youtube.com/watch?v=EhJ-mG5eMmI), compared to the expected result heard in [this video](https://www.youtube.com/watch?v=4bnmcYJHNCo).

I'm not sure how much this counts as a bug since it happens on some original hardware, but I figure it's worth writing up.

## Steps to reproduce the problem
Start Soul Blazer (USA).sfc and listen to the music. It's most noticeable in the drums.

## ROM name and hash value
From the SmokeMonster pack:
8438da09de8ce9aded3bb08644543f7b60fb60cffc68ce2d67d6a0643f2ecfc2	SD2SNES/1 US - S/Soul Blazer (USA).sfc	f2832eb02547c39cae3bdaab5c2a53e4f8b31810	83cf41d53a1b94aeea1a645037a24004	31b965db

## firmware version 
- Jailbreak firmware v6.5

**Comment by SmokeMonsterPacks** [comment]
Illuminerdi on Discord confirmed that this happens on original hardware as well, so it's not exactly a bug and I will close the issue. If anything, it shows how faithful the SNT is to real hardware that it exhibits some characteristics of 1chips.
