### ISSUE TITLE
Reword instructions in README

### ISSUE THREAD

**Issue by soegaard** [SmokeMonsterPacks/Super-NT-Jailbreak#62]
The README says:
> The console LED will turn red and flicker while the firmware is flashed. This process may take a few 
> minutes. The main menu will load when it finishes. Delete the firmware file from your SD card after 
> flashing.

The problem is that the process is not over, when the LED stops blinking.
Therefore you get the impression that something went wrong.

Instead of "few" write the actual number(or add, say, 1) of minutes.

**Comment by SmokeMonsterPacks** [comment]
Thanks for the suggestion. I've updated the README to try to make the process more intuitive. I can't add an exact time for the flashing process, since it can vary based on the speed of the SD card used.

**Comment by soegaard** [comment]
> The main menu will load when it has finished flashing.

This sentence should mention, that there is a considerable pause between the finished flashing and the appearing of the main menu.

**Comment by SmokeMonsterPacks** [comment]
OK, I've fixed it. I think it's perfect now. Please let me know what you think.
