### ISSUE TITLE
Glitches: Zelda ALTTP (USA) Cartridge's saves lost after crash

### ISSUE THREAD

**Issue by klinker41** [SmokeMonsterPacks/Super-NT-Jailbreak#67]
While playing Link to the Past last night on an official USA cartridge, I ran into what appeared to be a crash that also wiped out my save data on the cart. I was about an hour and a half into the game, bonked on a rock (nothing out of the ordinary there :) ) and all of a sudden the sound glitched out a little bit and the screen went black. I was still able to access the menu via the hotkey. I waited here for a few minutes to make sure nothing was going to change, then pressed the reset button on the console. When the cartridge booted back up the screen remained black. I then powered off the system, booted up again and went into the cartridge and the screen was still black. Finally, I powered off, removed the cart and powered back on. This time it booted up properly, but my saved data had been cleared.

The cartridge is the official USA version of the game and I'm running the latest JB 6.5 firmware with stock settings. No SD card was inserted at the time.

Let me know if there is any way to grab logs from the system or anything like that! I know problems like this can be very difficult to solve since I can't really provide reproduction steps, but I'd like to help in any way I can if possible. Also, sorry if this isn't the right place to report the problem, it doesn't seem jailbreak specific, so feel free to close if that is the case and I can report elsewhere.

**Comment by frederic-mahe** [comment]
@klinker41 thanks for reporting this issue, and sorry you lost your saved progress. The Super Nt does not produce logs as it does not run an OS _per se_, so there is not much you can do there. _A Link to the Past_ is a very popular game, let's see if someone else can reproduce a similar issue.

**Comment by klinker41** [comment]
No problem, I don't ever mind replaying it :) thanks for the quick response and I'll also be trying to reproduce.

**Comment by SmokeMonsterPacks** [comment]
I've had a couple of users suggest that this may be a problem with your cart. Are the pin connectors perfectly clean? Supposedly this would happen if the cart is disconnected during a save.

**Comment by klinker41** [comment]
The connectors seem clean to me. I just purchased the cart and haven't played it on an OG SNES, so it's very possible that the problem could be on the carts side and not the super nt, I hadn't considered this before.

**Comment by SmokeMonsterPacks** [comment]
I'm going to close this until another user can replicate it.
