### ISSUE TITLE
Improvement: Screen Boundary Box

### ISSUE THREAD

**Issue by Bits-n-Stuff** [SmokeMonsterPacks/Super-NT-Jailbreak#68]
**REQUESTED FEATURES**
An option to set a simple white outline on the very edge of the configured display area to assist in people setting up a custom display area. Maybe the outer 1 pixel, 2 pixels or 3 pixels could be solid white.
**REQUESTED FEATURES - AMENDMENT** : If this is implemented, it may actually be worth adding it as a graphical option while playing games too.

**REASON**
Different games use different amounts of the available display area to display graphics, quite a few games can have black borders around the horizontal and/or vertical display area. This can make it really awkward to configure the screen dimensions as this varies so much from game to game. One game that may reach the top and the bottom of your TV screen could then cause overscan in the next game you play.

Having the Screen Boundary Box will allow people to always see the outer limits of the display area irrelevant of the game they're configuring it for.
**REASON - AMENDMENT** : It's an option that seems pretty common for older retro emulated games on current consoles. I don't use it myself but I assume that as companies implement it, there are people who do prefer it and if it's in the firmware to aid setting up as I suggested then it may as well also be an option for anybody who wants it.

**WHICH GAMES**
It's not a particular game or series of games, some just appear to render fewer pixels than others, perhaps to aid performance.

**FIRMWARE VERSION**
Not in Official v4.4
Not in Jailbreak v6.5

**Comment by B9KnM8UqQ2W2Vwk7uvZ7** [comment]
I've added an amendment to this, it's about the initial request and adding an additional option to it rather than it being a completely new request.

**Comment by SmokeMonsterPacks** [comment]
Closing minor feature requests to shift the focus back on bugs.

**Comment by kylophone** [comment]
Doesn't the 240p Test Suite already do something like this?
