### ISSUE TITLE
Glitches: Front Mission (USA) shaking text on maps

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [SmokeMonsterPacks/Super-NT-Jailbreak#71]
I'm copying this bug report over from [Nerdly Pleasures blog](https://nerdlypleasures.blogspot.com.br/2018/02/super-nt-review-ideal-fpga-console.html). Could someone please verify this and post their ROM's hash?

> Front Mission (shaking text box on map screens sometimes)

## firmware version and SD card model
- Jailbreak firmware version: Occurs on all firmware revisions

**Comment by SmokeMonsterPacks** [comment]
RaspberryAlpine couldn't reproduce this bug via SD2SNES

ROM Tested: Front Mission - Gun Hazard (J) [T+Eng1.01_AGTP].smc 
SNT Firmware: 4.4

**Comment by SmokeMonsterPacks** [comment]
Kev has a fix for Front Mission coming in the next firmware update.

**Comment by SmokeMonsterPacks** [comment]
Closed until someone tests in JB v6.6. Please comment if it needs to be re-opened.

**Comment by SmokeMonsterPacks** [comment]
Great Hierophant is still getting shaking text when loading Front Mission via SD2SNES. It does not occur when the ROM is via SD in the Jailbreak FW however.

Could someone please test the real cart to see if the bug is SD2SNES-specific?

**Comment by G-lithcz** [comment]
The bug can be easily reproduced by starting up Front Mission (not Front Mission: Gun Hazard - totally separate game) from a cartridge and waiting 15 seconds or so before a text box appears on the world map. The text will be shaking. If it is not shaking restart the game and it should appear after one or two restarts.

**Comment by SmokeMonsterPacks** [comment]
Please test in the latest fw

**Comment by tjanas** [comment]
I saw the shaking text with the latest firmware.

**Comment by GunbusterZero** [comment]
I am on latest JB 7.0 firmware, can confirm shaking text too.

**Comment by tjanas** [comment]
Apparently this cartridge wasn't an officially licensed cartridge, but rather a very old unofficial translation on a repro cart.
