### ISSUE TITLE
Legends of Mario (SMW hack) - No save dialog using select+down

### ISSUE THREAD

**Issue by cdub1a** [SmokeMonsterPacks/Super-NT-Jailbreak#79]
The pop-up dialog with the option to "save" or "cancel" does not show.  Save works in emulator.

Firmware JB6.5
Rom: LegendsOfMario_v1.2.sfc

MD5 hash of LegendsOfMario_v1.2.sfc:
b3060b012f71ac28ddaac1e45dd4ea76

**Comment by SmokeMonsterPacks** [comment]
I'm going to close all SMW hack reports unless they are tested and working on real SNES hardware. The SMW hacking scene is notorious for only testing in emulation and not verifying their work on real hardware.
