### ISSUE TITLE
Firmware Checksum: Upstream Request

### ISSUE THREAD

**Issue by jan-kleks** [SmokeMonsterPacks/Super-NT-Jailbreak#8]
So that people know the file was not corrupted, for instance, during downloading.

**Comment by SmokeMonsterPacks** [comment]
Great idea, thanks. I'll add it to the README.

**Comment by SmokeMonsterPacks** [comment]
Done, thanks again.

**Comment by frederic-mahe** [comment]
In my opinion, that should be solved upstream by creating a MD5SUM file alongside the firmware:
```sh
md5sum snt_firmware_verJB6.4.bin > MD5SUM
```
If this is done before the first network transfer, then we can be pretty sure that the file is not corrupted.

**Comment by frederic-mahe** [comment]
I've just added a _post-facto_ MD5SUM, but that should be done upstream.

**Comment by SmokeMonsterPacks** [comment]
I've put in a request upstream for checksums to be included with firmwares going forward.

**Comment by SmokeMonsterPacks** [comment]
No follow up. Issue marked as resolved.

**Comment by SmokeMonsterPacks** [comment]
Upstream MD5 checksums added for both releases.
