### ISSUE TITLE
Glitches: Rendering Ranger 2 (ALL) Fix incoming

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [SmokeMonsterPacks/Super-NT-Jailbreak#80]
Just a PSA: There's no need to troubleshoot the RR2 issues too heavily--Kev has a fix incoming in the next official firmware update.

**Comment by Rahzadan** [comment]
Just tested on 4.5 - I can confirm this is now fixed!

**Comment by SmokeMonsterPacks** [comment]
Thanks, @Rahzadan!
