### ISSUE TITLE
Glitches: Uncompressed/Decrypted Star Ocean (J) loads to blank screen

### ISSUE THREAD

**Issue by ThePfhor** [SmokeMonsterPacks/Super-NT-Jailbreak#81]
ROM is presented as being loaded up but then a blank screen is presented and the game does not start. I am able to access the Super Nt menu though after it loads.

- firmware version: 6.5

**Comment by SmokeMonsterPacks** [comment]
I passed this bug along to the jailbreaker a few weeks back and they are looking in to it. The SNT has 16mb of RAM for loading games, so it may be possible to get SO decompressed working on it. Theoretically at least. Fingers crossed that it's something small and not a hardware limitation.

**Comment by Rahzadan** [comment]
> Tested and working on SD2SNES on an SNES.

I can also confirm that this ROM works fine on an SD2SNES via Super Nt (Firmware 4.4)

**Comment by SmokeMonsterPacks** [comment]
This is fixed in v6.6

**Comment by ThePfhor** [comment]
Thank you!
