### ISSUE TITLE
Super NT official firmware update v4.5 & Jailbreak v6.6

### ISSUE THREAD

**Issue by frederic-mahe** [SmokeMonsterPacks/Super-NT-Jailbreak#85]
https://support.analogue.co/hc/en-us/articles/360000557452-Super-Nt-Firmware-Update-v4-5

**v4.5 notes:**
- Fixed *Rendering Ranger R2* / *Targa*.
- Fixed *Unholy Night* crash/graphics issue.
- Fixed an issue with *Marvelous: Another Treasure Island* works now without graphic glitches.
- Fixed an issue with *Chrono Trigger* crashing on entering save menu.
- Fixed *Flashback*’s audio buzz when entering inventory.
- Fixed *Arabian Nights* audio feedback issue.
- Fixed *Tiny Toons Buster Busts Loose* audio crash
- Fixed *Batman Returns* audio crash
- Fixed the RGB value -1 fix again to remove vertical zebra stripes.
- Fixed “menu bounce” setting so it shows up again.
- Changed wording of the checkbox in the cheat codes. It now says “enable checked codes” to reduce confusion.
- Changed “tools” menu to “cheat codes”.
- Added a “disable hotkeys” feature under hot keys. This lets you disable all hotkeys and controller auto polling until power is cycled.
- Added debugger under “hardware” menu (probably not the most useful for most people but I use it a lot so someone developing a game might find it useful).

**Jailbreak [v6.6](https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/releases/tag/v6.6)**

  - All official v4.5 fixes plus:
  - Added CopySNES. Lets you dump carts/save RAM to the SD card. Files are placed into /COPYSNES/. The directory is created if it does not exist. See the [text](https://github.com/SmokeMonsterPacks/Super-NT-Jailbreak/releases/download/v6.6/CopySNES.Instructions.txt) file for full instructions.
  - Star Ocean 96mbit works now.
  - Changed menu operation so that if you enter the settings menu in the file browser, it can be exited back to the file browser by hitting select (or backing all the way out using the back button).
  - Changed file browser operation so that if you attempt to back out of it, you get warned that the running game will be ended and you cannot save any more.
  - In JB mode, `tools` menu appears on the main menu which has CopySNES and cheat codes.
  - `Cheat codes` is moved into the file browser settings menu.

<details>
  <summary>Click to expand full CopySNES instructions</summary>
<BR>
CopySNES is designed to be an easy to use way to back up cartridge ROMs and save RAM data. Most types of cartridges are supported, and if it isn't specifically supported or for some reason the cartridge header is bad, the settings can be changed.

How to use it

* Power the system off
* Insert cartridge
* Power the system on
* Select "CopySNES" on the tools menu

At this point, CopySNES will query the cartridge and grab the header and attempt to detect what kind of cartridge it is.

You have two options at this point:

1) hit "enter" to accept the settings and proceed to saving.  (note: editing the name will happen during the save step). (skip to "filename entry" below)

2) hit "start" to edit the detected settings (note: editing the name will happen during the save step.)

If you wish to edit the settings, use up and down to select one of the settings, then use left and right to adjust it.  You can select between 32K and 16Mbytes of ROM to dump, and between 0K (i.e. none) and 32K of RAM. 

Finally, you can select the type of mapper it is, i.e. LOROM, HIROM, EXHIROM, or EXLOROM. There is also a "FLAT" setting which will let you dump the entire SNES cartridge space if desired. FLAT starts at address 00:0000 and will dump the specified amount of memory.   

While you can dump say, 8Mbyte of LOROM or HIROM, doing so most likely won't be very useful.  

This "manual" mode is useful when dumping things that do not have a valid or any header such as the Game Genie BIOS (it reports 0K of ROM and is actually 64K) or the Sufami Turbo (again, it reports 0K of ROM even though it's really 1MByte).

When you are done adjusting the settings, and are ready to dump, hit "select".

Filename entry:

At this point the filename can be edited.  It will directly copy the ROM header name in here. For some Japanese titles, there may be no valid ASCII in the header (or if there's no header at all) so any invalid characters for a filename are replaced with spaces. If there's no name at all, it will default to "GAME".  Use up/down to change the character's value and left/right to select a character. Press "enter" to accept the filename and begin the dumping process.

The game's actual size will be determined at this point (i.e. a 2MByte game reported in the header might only be 1.5Mbytes, so this will be detected now).

Finally, the ROM and RAM are dumped to the SD card.

Now that the dump is complete, you are returned to the tools menu. The system can be powered off and a new cartridge inserted to dump, and so on until all the carts are dumped that you wish to dump.

The following things have been tested:

* LOROM   (ROM + RAM)
* HIROM   (ROM + RAM)
* EXHIROM (ROM + RAM)
* SDD-1   (ROM + RAM)
* SA-1    (ROM + RAM)
* GSU-1/2 (ROM + RAM)
note: For SuperFX (GSU), the RAM is always dumped as 64K.  This is because games such as Yoshi's Island have RAM, but the headers for all the games show 0K of RAM.  This 'larger' RAM will work with the major emulators, and can be trimmed down later if needed.  
* CX4     (ROM)
* DSP1-4  (ROM + RAM)
* S-RTC   (ROM,  RAM is dumped but it is unknown if it works)
* ST010   (ROM)
* ST011   (ROM)
* ST018   (ROM)
* OBC-1   (ROM + RAM)
* SPC7110 (ROM + RAM, but RAM has not been verified to work)

Note: Testing with no$sns, it will not use the saves on certain games such as Chrono Trigger. I don't know why, the saves are good and work on the Super NT itself.
</details>  
<BR>

**Comment by SmokeMonsterPacks** [comment]
Looks like Kev swung his mighty Glitch Hammer.
