### ISSUE TITLE
Improvement: CopySNES cannot write SRAM back to cart

### ISSUE THREAD

**Issue by Rahzadan** [SmokeMonsterPacks/Super-NT-Jailbreak#86]
## Expected behavior

Ability to write SRAM back to cart after it has been read/dumped (useful for changing cartridge batteries, for example).

## Actual behavior

CopySNES function cannot write SRAM back to the cart. Appears to be read-only.

## firmware

- firmware version: Jailbreak v6.6

**Comment by SmokeMonsterPacks** [comment]
This is a feature request. I'm going to close it to keep the clutter down.
