### ISSUE TITLE
Improvement: Have save loading and CopySNES collude on save locations

### ISSUE THREAD

**Issue by bsstephan** [SmokeMonsterPacks/Super-NT-Jailbreak#91]
## Background

The jailbreak functionality of loading ROMs and SRAM from the SD card is cool. The CopySNES functionality of saving SRAM to the SD card is cool. Unfortunately, the two use different paths and naming standards, so even after you dump a cart's SRAM to SD, the jailbreak firmware doesn't load it. You have to mount the SD card on your PC and move the .srm file and rename it to .sav, if you want to play your dumped SRAM via the jailbreak firmware.

## Ideas

There are (at least?) three ways you could sync the dumping and the loading functionality, depending on which codebase is easier to modify. My ideas:

* Change the jailbreak loading to match /COPYSNES/*.srm files as the first location to detect saves.
* Change the jailbreak loading to look in the current working directory (i.e. where you loaded the ROM from) as the first location to detect saves.
* Change the CopySNES dumping of the SRAM to also write to /SAVES/*.sav, or copy the file after the fact.

Certainly this is only a quality of life-type change, but it would be cool if these two parts of the firmware were a bit more in sync with each other.

**Comment by SmokeMonsterPacks** [comment]
Closing minor feature requests to shift the focus back on bugs. This issue will still be publicly visible however.
