### ISSUE TITLE
Glitches: Unholy Night (U) CopySNES dump error

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [SmokeMonsterPacks/Super-NT-Jailbreak#93]
Unholy Night plays from cart and SD perfectly. However, RevQuixo dumped his English Unholy Night cart via CopySNES and the resulting ROM crashes after finishing the first match. The original cart works fine though.

MD5: ffe5445ac39f30efc397899351d12b07 - Dumped twice with the same result (MD5 match).
FW: Jailbreak v6.6

**Comment by SmokeMonsterPacks** [comment]
bss has confirmed this issue with his cart dump as well.

**Comment by bsstephan** [comment]
Yup, same behavior, ROM dumped via CopySNES crashed after I won the first match.

For whatever it's worth, playing a Retrode-sourced dump off of my SD2SNES works fine too.

**Comment by TheRealFlamepanther** [comment]
Happened with mine too.

**Comment by SmokeMonsterPacks** [comment]
I'm going to close reports for game that dump incorrectly. If a game doesn't dump right, you need to adjust the settings manually. There will be games that never dump though, and these will not get fixes I'm told.
