### ISSUE TITLE
Super Gameboy 2 menu combo triggers Super NT menu

### ISSUE THREAD

**Issue by t3rminus** [SmokeMonsterPacks/Super-NT-Jailbreak#95]
On a Super Gameboy 2 (SGB2), pressing the menu button combo (`L+R`) triggers the Super NT menu, if the Super NT menu hotkey is set to `Start+Select`

## Expected Behavior
Only the SGB2 menu is shown

## Actual Behavior
The SGB2 menu opens, but also the Super NT Menu, even though the Super NT hotkeys weren't touched.

## Steps to reproduce the problem
1. Set the Super NT menu hotkey to `Start+Select`
2. Start the Super Gameboy 2, with any game
3. Press `L+R` simultaneously to open the SGB2 menu
4. Super NT menu opens.

## firmware
- firmware version: JB 6.5

## relevant Super Nt settings
- Must have Super NT menu hotkey set to `Start+Select`

**Comment by SmokeMonsterPacks** [comment]
This is the 8bitdo receiver Known Issue noted in the readme.
