### ISSUE TITLE
Improvement: Settings, Hide Super Turrican

### ISSUE THREAD

**Issue by golabki** [SmokeMonsterPacks/Super-NT-Jailbreak#96]
This is minor, but it would be nice to have the ability to simplify the main menu by having the option to hide each Super Turrican game that is preloaded on the system.

Or perhaps nest the games in "Browse System," similar to "Browse SD Card."

**Comment by masterninjah** [comment]
this would be great because ive accidentally started one of the games trying to get to the setting,  really sucks when youre playing a cartridge.

**Comment by Shiftone** [comment]
Wondering why this was closed without comment?

I too would like a way to remove the built in games - they have a negative effect on the UX in their current location.

**Comment by jhnbkr** [comment]
+1 for me on this request.
